version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "apps/api"
    schedule:
      interval: "weekly"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "apps/ui"
    schedule:
      interval: "weekly"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "tests/ui"
    schedule:
      interval: "weekly"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "docker"
    directory: "apps/api"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "apps/ui"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "apps/k6"
    schedule:
      interval: "weekly"
