{{- range $key, $deployment := .Values.deployments }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kube-score/ignore: container-security-context-readonlyrootfilesystem,container-security-context-user-group-id,container-image-pull-policy,pod-networkpolicy,container-image-tag
  name: {{ $deployment.name }}-deployment
  labels:
    app: {{ $deployment.name }}
spec:
  replicas: {{ $deployment.replicas }}
  selector:
    matchLabels:
      app: {{ $deployment.name }}
  template:
    metadata:
      labels:
        app: {{ $deployment.name }}
    spec:
      serviceAccountName: thrashbuddy-runner-sa
      containers:
        - name: {{ $deployment.name }}
          image: "{{ $.Values.global.imageRepoPrefix }}{{ $deployment.image }}"
          imagePullPolicy: IfNotPresent
          readinessProbe:
            tcpSocket:
              port: {{ $deployment.livenessPort }}
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              cpu: {{ $deployment.resources.requests.cpu | quote }}
              memory: {{ $deployment.resources.requests.memory | quote }}
              ephemeral-storage: {{ $deployment.resources.requests.ephemeralStorage | quote }}
            limits:
              cpu: {{ $deployment.resources.limits.cpu | quote }}
              memory: {{ $deployment.resources.limits.memory | quote }}
              ephemeral-storage: {{ $deployment.resources.limits.ephemeralStorage | quote }}
          env:
          - name: IMAGE_REPO_PREFIX
            value: "{{ $.Values.global.imageRepoPrefix }}"
          - name: K6_INFLUXDB_TOKEN
            valueFrom:
              secretKeyRef:
                name: thrashbuddy-secrets
                key: INFLUXDB_API_TOKEN
          {{- if $deployment.env }}
          {{- range $key, $value := $deployment.env }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
          {{- end }}
{{- end }}
