apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.release }}-runner-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: {{ .Values.release }}-runner-sa
    namespace: default
roleRef:
  kind: Role
  name: {{ .Values.release }}-runner-role
  apiGroup: rbac.authorization.k8s.io
