deployments:
  ui:
    name: ui
    image: thrash-buddy/ui:latest
    replicas: 1
    pdbMinAvailable: 1
    livenessPort: 80
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
        ephemeralStorage: 500Mi
      limits:
        cpu: 500m
        memory: 512Mi
        ephemeralStorage: 1Gi
    env: {}
  api:
    name: api
    image: thrash-buddy/api:latest
    replicas: 1
    pdbMinAvailable: 1
    livenessPort: 8080
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
        ephemeralStorage: 500Mi
      limits:
        cpu: 500m
        memory: 512Mi
        ephemeralStorage: 1Gi
    env:
      MINIO_URL: "http://minio.default.svc.cluster.local:9000"
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECRET_KEY: "minioadmin"
      MINIO_BUCKET: "thrash-buddy"

services:
  ui:
    name: ui
    type: ClusterIP
    port: 80
    targetPort: 80
  api:
    name: api
    type: ClusterIP
    port: 8080
    targetPort: 8080

ingress:
  enabled: true
  basicauth: false
  className: nginx
  host: ""
  rules:
    - path: /
      pathType: Prefix
      serviceName: ui
      servicePort: 80
    - path: /api
      pathType: Prefix
      serviceName: api
      servicePort: 8080

global:
  imageRepoPrefix: ""
