{
 "title": "k6 Metrics",
 "panels": [
  {
   "title": "HTTP Reqs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_reqs\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\r\n  |> group()\r\n  |> sum()\r\n  |> yield(name: \"http_reqs_total\")\r\n\r\n"
    }
   ]
  },
  {
   "title": "Failed HTTP Reqs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"array\"\r\n\r\nreal = from(bucket: \"metrics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_reqs_failed\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n\r\nfallback = array.from(rows: [\r\n  {\r\n    _time: v.timeRangeStart,\r\n    _value: 0.0,\r\n    _field: \"value\",\r\n    _measurement: \"http_reqs_failed\",\r\n    _start: v.timeRangeStart,\r\n    _stop: v.timeRangeStop\r\n  }\r\n])\r\n\r\nunion(tables: [real, fallback])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\r\n  |> group()\r\n  |> sum()\r\n  |> yield(name: \"http_reqs_total\")\r\n"
    }
   ]
  },
  {
   "title": "Data IN",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"array\"\r\n\r\nreal = from(bucket: \"metrics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"data_received\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n\r\nfallback = array.from(rows: [\r\n  {\r\n    _time: v.timeRangeStart,\r\n    _value: 0.0,\r\n    _field: \"value\",\r\n    _measurement: \"http_reqs_failed\",\r\n    _start: v.timeRangeStart,\r\n    _stop: v.timeRangeStop\r\n  }\r\n])\r\n\r\nunion(tables: [real, fallback])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\r\n  |> group()\r\n  |> sum()\r\n  |> yield(name: \"http_reqs_total\")\r\n"
    }
   ]
  },
  {
   "title": "Data OUT",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"array\"\r\n\r\nreal = from(bucket: \"metrics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"data_sent\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n\r\nfallback = array.from(rows: [\r\n  {\r\n    _time: v.timeRangeStart,\r\n    _value: 0.0,\r\n    _field: \"value\",\r\n    _measurement: \"http_reqs_failed\",\r\n    _start: v.timeRangeStart,\r\n    _stop: v.timeRangeStop\r\n  }\r\n])\r\n\r\nunion(tables: [real, fallback])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\r\n  |> group()\r\n  |> sum()\r\n  |> yield(name: \"http_reqs_total\")\r\n"
    }
   ]
  },
  {
   "title": "VUs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vus\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> drop(columns: [\"url\", \"status\", \"scenario\"]) // Drop irrelevant tags\r\n  |> aggregateWindow(every: 10s, fn: mean, createEmpty: false)\r\n  |> group(columns: [\"_time\"]) // group by time to sum all relevant points per timestamp\r\n  |> sum(column: \"_value\")\r\n  |> group() // Optional: ungroup after sum for a single clean line\r\n  |> yield(name: \"summed_vus\")\r\n"
    }
   ]
  },
  {
   "title": "Reqs Durations",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 20, "x": 0, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_duration\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> group(columns: [\"name\"]) \r\n  |> aggregateWindow(every: 5s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  }
 ]
}
{
 "title": "Cluster metrics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"_monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_user\")\r\n  |> filter(fn: (r) => r[\"cpu\"] == \"cpu-total\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"_monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"free\" or r[\"_field\"] == \"used\" or r[\"_field\"] == \"total\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"_monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_recv\" or r[\"_field\"] == \"bytes_sent\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}