deployments:
  frontend:
    name: frontend
    image: cloud-thrash/frontend:latest
    replicas: 1
    pdbMinAvailable: 1
    livenessPort: 80
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
        ephemeralStorage: 500Mi
      limits:
        cpu: 500m
        memory: 512Mi
        ephemeralStorage: 1Gi
    env: {}
  backend:
    name: backend
    image: cloud-thrash/backend:latest
    replicas: 1
    pdbMinAvailable: 1
    livenessPort: 8080
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
        ephemeralStorage: 500Mi
      limits:
        cpu: 500m
        memory: 512Mi
        ephemeralStorage: 1Gi
    env:
      MINIO_URL: "http://minio.default.svc.cluster.local:9000"
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECRET_KEY: "minioadmin"
      MINIO_BUCKET: "cloud-thrash"

services:
  frontend:
    name: frontend
    type: ClusterIP
    port: 80
    targetPort: 80
  backend:
    name: backend
    type: ClusterIP
    port: 8080
    targetPort: 8080

ingress:
  enabled: true
  basicauth: false
  className: nginx
  host: ""
  rules:
    - path: /
      pathType: Prefix
      serviceName: frontend
      servicePort: 80
    - path: /api
      pathType: Prefix
      serviceName: backend
      servicePort: 8080

global:
  imageRepoPrefix: ""
