name: Quality Gate

on:
    pull_request:
        branches: [develop]

    push:
        branches: [develop]

    workflow_dispatch:

permissions:
    contents: read
    issues: read
    checks: write
    pull-requests: write

jobs:
    backend:
        name: Backend Analysis
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  submodules: true
                  fetch-depth: 0
            - name: Install Dependencies and Run Unit Tests
              working-directory: ./services/backend
              run: ./gradlew clean jacocoTestReport
            - name: Publish Test Results
              uses: EnricoMi/publish-unit-test-result-action/linux@v2
              if: always()
              with:
                  check_name: "Backend Unit Tests"
                  files: |
                      ./services/backend/build/test-results/**/*.xml
            - name: Generate Backend Coverage Summary
              uses: irongut/CodeCoverageSummary@v1.3.0
              with:
                  filename: ./services/backend/build/reports/jacoco/test/jacocoTestReport.xml
                  format: markdown
                  output: both
                  badge: true
            - name: Add Coverage Report to GitHub Summary
              if: always()
              run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
            - name: Comment Backend Coverage on PR
              if: github.event_name == 'pull_request'
              uses: peter-evans/create-or-update-comment@v4
              with:
                  issue-number: ${{ github.event.pull_request.number }}
                  body-file: code-coverage-results.md
                  token: ${{ secrets.GITHUB_TOKEN }}

    frontend:
        name: Frontend Analysis
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  submodules: true
                  fetch-depth: 0
            - name: Install Dependencies
              working-directory: ./services/frontend
              run: ./npmw install
            - name: Unit Tests and Coverage
              working-directory: ./services/frontend
              run: ./npmw run test:ci
            - name: Show Coverage Summary in PR
              uses: irongut/CodeCoverageSummary@v1.3.0
              with:
                  filename: ./services/frontend/coverage/cloud-thrash/coverage.xml
                  badge: true
                  fail_below_min: true
                  format: markdown
                  output: both
                  thresholds: "60 80" # optional: warn under 80%, fail under 60%
            - name: Append Coverage Report to GitHub Summary
              if: always()
              run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
            - name: Post Coverage Comment to PR
              if: github.event_name == 'pull_request'
              uses: peter-evans/create-or-update-comment@v4
              with:
                  issue-number: ${{ github.event.pull_request.number }}
                  body-file: code-coverage-results.md
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Lint
              working-directory: ./services/frontend
              run: ./npmw run lint
            - name: Publish Test Results
              uses: EnricoMi/publish-unit-test-result-action/linux@v2
              if: always()
              with:
                  check_name: "Frontend Unit Tests"
                  files: |
                      ./services/frontend/TESTS-Chrome_Headless_*.xml

    infra-and-images:
        concurrency:
            group: "test--infra-group-${{ github.event.pull_request.number }}"
            cancel-in-progress: false
        if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' # takes too long for pushes
        needs: [backend, frontend]
        name: Infrastructure and Images
        runs-on: self-hosted
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
              with:
                  submodules: true
            - name: Write .env file
              run: |
                  echo "${{ secrets.DOT_ENV }}" > ./infrastructure/helm/.env
            - uses: hadolint/hadolint-action@v3.1.0
              with:
                  dockerfile: ./services/backend/Dockerfile
                  ignore: DL3018
            - uses: hadolint/hadolint-action@v3.1.0
              with:
                  dockerfile: ./services/frontend/Dockerfile
                  ignore: DL3018
            - uses: hadolint/hadolint-action@v3.1.0
              with:
                  dockerfile: ./services/k6/Dockerfile
                  ignore: DL3018

            - name: Docker Cleanup
              run: |
                  docker stop $(docker ps -q) || true
                  docker rm -f $(docker ps -aq) || true
                  docker rmi -f $(docker images --filter "dangling=true" -q) || true
                  docker system prune -a --volumes -f
                  docker builder prune -a -f
                  docker ps -aq
                  docker images
                  docker volume ls
                  docker network ls

            - name: Build Docker Images
              run: |
                  infrastructure/docker/build-all.sh
                  docker images

            - name: Set up Kubernetes with Minikube
              working-directory: ./infrastructure/helm
              run: |
                  minikube delete --all
                  minikube start --driver=docker
                  ./load.sh
            - name: Helm
              working-directory: ./infrastructure/helm
              run: |
                  ./install.sh
            - name: frontend tests
              working-directory: ./services/frontend-test
              run: |
                  nohup minikube tunnel > /dev/null 2>&1 &
                  # Wait for the ingress-nginx-controller to be ready before setting the BASE_URL for Playwright tests
                  sleep 10
                  INGRESS_IP=$(kubectl get svc ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
                  export BASE_URL="http://$INGRESS_IP/app/index.html"
                  npm ci
                  ./npmw install 
                  ./npmw test
            - name: Archive Playwright Test Results
              uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: report.zip
                  path: services/frontend-test/test-results
                  retention-days: 7
            - name: Minikube delete cluster
              if: always()
              run: minikube delete --all
